version: '3.9'
services:
  
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/usr/src/app
    restart: always
    networks:
      - queue-net

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '5173:5173'
    restart: always
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - queue-net
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/www.scales.uxlivinglab.online/fullchain.pem:/etc/letsencrypt/live/www.scales.uxlivinglab.online/fullchain.pem:ro
      - /etc/letsencrypt/live/www.scales.uxlivinglab.online/privkey.pem:/etc/letsencrypt/live/www.scales.uxlivinglab.online/privkey.pem:ro
    restart: always
    networks:
      - queue-net
    depends_on:
      - backend
      - frontend
networks:
  queue-net:
    driver: bridge