version: '3.9'
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - '8001:8001'
    volumes:
      - ./backend:/usr/src/app
    restart: always
    networks:
      - queue-net

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '5173:5173'
    restart: always
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - queue-net
    depends_on:
      - backend
      - server

  mongo:
    container_name: mongo_container
    image: 'mongo'
    volumes:
      - mongo-data:/data/db
    networks:
      - queue-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --bind_ip_all
    restart: always
  
  server:
    container_name: server_container
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      PORT: ${PORT}
      MONGO_DB_URI: ${MONGO_DB_URI}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY}
      JWT_EXPIRY: ${JWT_EXPIRY}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - queue-net


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/www.scales.uxlivinglab.online/fullchain.pem:/etc/letsencrypt/live/www.scales.uxlivinglab.online/fullchain.pem:ro
      - /etc/letsencrypt/live/www.scales.uxlivinglab.online/privkey.pem:/etc/letsencrypt/live/www.scales.uxlivinglab.online/privkey.pem:ro
    restart: always
    networks:
      - queue-net
    depends_on:
      - backend
      - frontend

networks:
  queue-net:
    driver: bridge

volumes:
  mongo-data:
